import { OrderFormData } from './types'

export const initialFormData: OrderFormData = {
  vin: '',
  vinUnknown: false,
  address: '',
  earliestDate: '',
  notes: '',
  customerEmail: '',
  vehicleYear: '',
  vehicleMake: '',
  vehicleModel: '',
  servicesRequired: {},
}

export const ALLOWED_MAKES = new Set([
  'ACURA',
  'ALFA ROMEO',
  'ASTON MARTIN',
  'AUDI',
  'BENTLEY',
  'BMW',
  'BUICK',
  'CADILLAC',
  'CHEVROLET',
  'CHRYSLER',
  'DODGE',
  'FERRARI',
  'FIAT',
  'FORD',
  'GENESIS',
  'GMC',
  'HONDA',
  'HYUNDAI',
  'INFINITI',
  'JAGUAR',
  'JEEP',
  'KIA',
  'LAMBORGHINI',
  'LAND ROVER',
  'LEXUS',
  'LINCOLN',
  'LOTUS',
  'MASERATI',
  'MAZDA',
  'MERCEDES-BENZ',
  'MINI',
  'MITSUBISHI',
  'NISSAN',
  'PORSCHE',
  'RAM',
  'ROLLS-ROYCE',
  'SUBARU',
  'TESLA',
  'TOYOTA',
  'VOLKSWAGEN',
  'VOLVO',
])

export const EXCLUDED_KEYWORDS = [
  'CHASSIS',
  'CAB',
  'COMMERCIAL',
  'MEDIUM DUTY',
  'HEAVY DUTY',
  'STRIPPED',
  'INCOMPLETE',
  'MOTORHOME',
  'RV',
  'BUS',
  'TRACTOR',
  'MOTORCYCLE',
  'SCOOTER',
  'ATV',
  'TRAILER',
  'VAN CAMPER',
  'MOTOR COACH',
  // Volvo specific exclusions
  'FH',
  'FM',
  'FMX',
  'NH',
  'VHD',
  'VNL',
  'VNM',
  'VNR',
  'VNX',
  'VT',
]

// List of allowed model patterns (for models that start with letters followed by numbers)
export const ALLOWED_MODEL_PATTERNS = [
  /^[A-Z]\d{1,2}$/, // Matches Q50, G35, etc.
  /^[A-Z][A-Z]\d{1,2}$/, // Matches QX50, GX460, etc.
  /^[A-Z]\d{3}[a-zA-Z]*$/, // Matches M340i, S560e, etc.
]
