DROP TABLE IF EXISTS fleet_vehicle_equipment CASCADE;
DROP TABLE IF EXISTS service_equipment CASCADE;
DROP TABLE IF EXISTS job_services CASCADE;
DROP TABLE IF EXISTS order_services CASCADE;
DROP TABLE IF EXISTS user_addresses CASCADE;

DROP TABLE IF EXISTS jobs CASCADE;
DROP TABLE IF EXISTS order_uploads CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS technicians CASCADE;
DROP TABLE IF EXISTS keys CASCADE;
DROP TABLE IF EXISTS equipment CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS fleet_vehicles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS addresses CASCADE;

DROP TYPE IF EXISTS customer_type CASCADE; 