import {
    getSupabaseClient,
    triggerSchedulerReplan,
    waitForReplan,
    readCurrentScenarioMetadata,
    readBaselineMetadata,
} from './utils';
import { SupabaseClient } from '@supabase/supabase-js';
// Do NOT import seeding functions here
// import { cleanupAllTestData } from '../../../../simulation/scripts/db/cleanup-staging';
// import { seedBaseline } from '../../../../simulation/scripts/db/seed/baseline';
// import { seedScenario_base_schedule } from '../../../../simulation/scripts/db/seed/scenarios/base_schedule';
import { ScenarioSeedResult, BaselineRefs } from '../../../simulation/scripts/db/seed/scenarios/types'; // Still needed for the type

// Increase Jest timeout for this potentially long-running test suite
// jest.setTimeout(90000); // 90 seconds - Alternatively set globally in jest.config.js

describe('Scheduler Integration - Base Schedule', () => {
    let supabase: SupabaseClient;
    // Variables to hold metadata read from files
    let currentScenarioResult: ScenarioSeedResult;
    let baselineRefs: BaselineRefs;
    // Use a fixed technician count for consistency in tests
    const technicianCount = 4;

    beforeAll(async () => {
        supabase = getSupabaseClient();

        console.log('--- Test Setup: Reading Metadata Files ---');
        try {
            // Read both metadata files generated by the external seeding process
            baselineRefs = await readBaselineMetadata();
            currentScenarioResult = await readCurrentScenarioMetadata();

            // Basic validation
            if (currentScenarioResult.scenarioName !== 'base_schedule') {
                throw new Error(`Expected scenario metadata for 'base_schedule', but found '${currentScenarioResult.scenarioName}'.`);
            }
            if (!baselineRefs.technicianIds || baselineRefs.technicianIds.length === 0) {
                throw new Error('Baseline metadata is missing technician IDs.');
            }
            if (!currentScenarioResult.insertedIds?.jobs || currentScenarioResult.insertedIds.jobs.length === 0) {
                throw new Error('Scenario metadata is missing job IDs.');
            }
            console.log(`Metadata loaded. Baseline Techs: ${baselineRefs.technicianIds.length}. Scenario: ${currentScenarioResult.scenarioName}. Scenario Jobs: ${currentScenarioResult.insertedIds.jobs.length}`);
            console.log('--- Test Setup Complete ---');

        } catch (error) {
            console.error('FATAL: Test setup failed while reading metadata:', error);
            // Throwing error in beforeAll will typically prevent tests from running
            throw error;
        }
    }, 30000); // Shorter timeout for beforeAll as it's just reading a file

    it('should schedule jobs correctly according to the base scenario after replan', async () => {
        // Ensure setup succeeded and we have metadata
        expect(baselineRefs).toBeDefined();
        expect(currentScenarioResult).toBeDefined();
        expect(baselineRefs.technicianIds).toBeDefined();
        expect(currentScenarioResult.insertedIds.jobs).toBeDefined();

        const scenarioJobIds = currentScenarioResult.insertedIds.jobs!;
        const validTechnicianIds = baselineRefs.technicianIds!;

        console.log('Triggering scheduler replan...');
        await triggerSchedulerReplan();

        console.log('Waiting for replan to complete...');
        const checkCondition = async (): Promise<boolean> => {
            const { data: jobs, error } = await supabase
                .from('jobs')
                .select('id, status')
                .in('id', scenarioJobIds)
                .eq('status', 'scheduled');

            if (error) {
                console.error('DB query error:', error);
                return false;
            }
            const allJobsScheduled = jobs !== null && jobs.length === scenarioJobIds.length;
            if (allJobsScheduled) {
                console.log(`Condition met: All ${scenarioJobIds.length} expected jobs are scheduled.`);
            } else {
                console.log(`Condition not met: Found ${jobs?.length ?? 0} scheduled jobs, expected ${scenarioJobIds.length}.`);
            }
            return allJobsScheduled;
        };
        await waitForReplan(checkCondition, 60000, 3000);

        console.log('Replan complete. Verifying schedule...');

        const { data: scheduledJobs, error: jobsError } = await supabase
            .from('jobs')
            .select('*, job_orders(*)')
            .in('id', scenarioJobIds)
            .order('scheduled_start_time', { ascending: true });

        expect(jobsError).toBeNull();
        expect(scheduledJobs).not.toBeNull();
        expect(scheduledJobs!.length).toEqual(scenarioJobIds.length);

        for (const job of scheduledJobs!) {
            expect(job.status).toEqual('scheduled');
            expect(job.scheduled_start_time).not.toBeNull();
            expect(job.assigned_technician_id).not.toBeNull();
            expect(validTechnicianIds).toContain(job.assigned_technician_id);
        }

        console.log('Base schedule verification successful.');
    });

    // afterAll(async () => {
    //     // Optional: Add cleanup specific to this test suite if needed,
    //     // though usually cleanup is handled by the next test's beforeAll.
    // });
}); 